# Generated by Django 5.1.6 on 2025-03-18 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_quiz_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Quizes'},
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='score_to_pass',
            new_name='requited_score_to_pass',
        ),
    ]
