# Generated by Django 5.1.6 on 2025-03-18 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_quiz_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='requited_score_to_pass',
            new_name='required_score_to_pass',
        ),
    ]
