# Generated by Django 5.1.6 on 2025-03-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='scheduled_publish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
