# Generated by Django 5.1.6 on 2025-03-11 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_post_featured_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='featured_image',
            new_name='image',
        ),
    ]
