# Generated by Django 5.1.6 on 2025-06-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_post_likes_alter_post_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='excerpt_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='excerpt_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_de',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
