# Generated by Django 5.1.6 on 2025-03-11 07:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bibleverse',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
