# Generated by Django 5.1.6 on 2025-03-11 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_rename_bibleverse_dailyverse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyverse',
            name='date',
            field=models.DateField(auto_now_add=True, unique=True),
        ),
    ]
