# Generated by Django 5.1.6 on 2025-03-12 08:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_alter_dailyverse_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyverse',
            name='date',
            field=models.DateField(default=datetime.date.today, unique=True),
        ),
        migrations.AlterField(
            model_name='dailyverse',
            name='reference',
            field=models.CharField(max_length=100),
        ),
    ]
