# Generated by Django 5.1.6 on 2025-03-12 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_alter_dailyverse_date_alter_dailyverse_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyverse',
            name='date',
            field=models.DateField(auto_now_add=True, unique=True),
        ),
    ]
